version: "2"
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
  method-complexity:
    config:
      threshold: 6
exclude_patterns:
  - "src/**/*.test.js"
  - "styles/uswds/"
