export const CLEAR_REPO = 'CLEAR_REPO'
export const OPEN_REPO = 'OPEN_REPO'
export const CLEAR_SITE_CONFIG = 'CLEAR_SITE_CONFIG'
export const SAVE_SITE_CONFIG = 'SAVE_SITE_CONFIG'
export const CLEAR_AGENCIES = 'CLEAR_AGENCIES'
export const SAVE_AGENCIES = 'SAVE_AGENCIES'
export const SAVE_FILTER_OPTIONS = 'SAVE_FILTER_OPTIONS'
export const SAVE_FILTER_SELECTIONS = 'SAVE_FILTER_SELECTIONS'

export const CLEAR_QUERY = 'CLEAR_QUERY'
export const UPDATE_QUERY = 'UPDATE_QUERY'

export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'
export const NEW_SEARCH = 'NEW_SEARCH'

export const CLEAR_BROWSE_FILTERS = 'CLEAR_BROWSE_FILTERS'
export const UPDATE_BROWSE_FILTERS = 'UPDATE_BROWSE_FILTERS'

export const CLEAR_SEARCH_FILTERS = 'CLEAR_SEARCH_FILTERS'
export const UPDATE_SEARCH_FILTERS = 'UPDATE_SEARCH_FILTERS'