export const LOAD_PROJECT = 'LOAD_PROJECT'

export const SAVE_AGENCIES = 'SAVE_AGENCIES'

export const SAVE_FILTER_OPTIONS = 'SAVE_BROWSE_FILTER_OPTIONS'

export const SAVE_FILTER_SELECTIONS = 'SAVE_FILTER_SELECTIONS'

// project details
export const UPDATE_REPO_ID = 'UPDATE_REPO_ID'

// browse projects
export const UPDATE_BROWSE_FILTERS = 'UPDATE_BROWSE_FILTERS'
export const UPDATE_BROWSE_PARAMS = 'UPDATE_BROWSE_PARAMS'
export const UPDATE_BROWSE_RESULTS = 'UPDATE_BROWSE_RESULTS'
export const UPDATE_BROWSE_FILTER_TAGS = 'UPDATE_BROWSE_FILTER_TAGS'

// search results
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'
export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS'
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS'
export const UPDATE_SEARCH_FILTER_TAGS = 'UPDATE_SEARCH_FILTER_TAGS'

// open tasks
export const SAVE_TASK_FILTER_OPTIONS = 'SAVE_TASK_FILTER_OPTIONS'
export const UPDATE_TASK_PARAMS= 'UPDATE_TASK_PARAMS'
export const UPDATE_TASK_RESULTS = 'UPDATE_TASK_RESULTS'
export const UPDATE_TASK_FILTER_TAGS = 'UPDATE_TASK_FILTER_TAGS'

// url
export const SYNC_URL_SEARCH_PARAMS = 'SYNC_URL_SEARCH_PARAMS'