export const LOAD_PROJECT = 'LOAD_PROJECT'

export const SAVE_AGENCIES = 'SAVE_AGENCIES'

export const SAVE_FILTER_OPTIONS = 'SAVE_BROWSE_FILTER_OPTIONS'

export const SAVE_FILTER_SELECTIONS = 'SAVE_FILTER_SELECTIONS'

// top menu
export const HIDE_SEARCH_DROPDOWN = 'HIDE_SEARCH_DROPDOWN'
export const SHOW_SEARCH_DROPDOWN = 'SHOW_SEARCH_DROPDOWN'
export const TOGGLE_SEARCH_DROPDOWN = 'TOGGLE_SEARCH_DROPDOWN'

// mobile menu
export const HIDE_MOBILE_MENU = 'HIDE_MOBILE_MENU'
export const SHOW_MOBILE_MENU = 'SHOW_MOBILE_MENU'
export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU'
export const EXPAND_MOBILE_MENU_OPTION = 'EXPAND_MOBILE_MENU_OPTION'
export const COLLAPSE_MOBILE_MENU_OPTION = 'COLLAPSE_MOBILE_MENU_OPTION'
export const COLLAPSE_ALL_MOBILE_MENU_OPTIONS = 'COLLAPSE_ALL_MOBILE_MENU_OPTIONS'
export const TOGGLE_MOBILE_MENU_OPTION = 'TOGGLE_MOBILE_MENU_OPTION'

// project details
export const UPDATE_REPO_ID = 'UPDATE_REPO_ID'

// browse projects
export const UPDATE_BROWSE_FILTERS = 'UPDATE_BROWSE_FILTERS'
export const UPDATE_BROWSE_PARAMS = 'UPDATE_BROWSE_PARAMS'
export const UPDATE_BROWSE_RESULTS = 'UPDATE_BROWSE_RESULTS'
export const UPDATE_BROWSE_FILTER_TAGS = 'UPDATE_BROWSE_FILTER_TAGS'

// browse agencies
export const UPDATE_AGENCIES_FILTERS = 'UPDATE_AGENCIES_FILTERS'
export const UPDATE_AGENCIES_PARAMS = 'UPDATE_AGENCIES_PARAMS'
export const UPDATE_AGENCIES_RESULTS = 'UPDATE_AGENCIES_RESULTS'
export const UPDATE_AGENCIES_FILTER_TAGS = 'UPDATE_AGENCIES_FILTER_TAGS'

// search results
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'
export const UPDATE_SEARCH_FILTERS = 'UPDATE_SEARCH_FILTERS'
export const UPDATE_SEARCH_PARAMS = 'UPDATE_SEARCH_PARAMS'
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS'
export const UPDATE_SEARCH_FILTER_TAGS = 'UPDATE_SEARCH_FILTER_TAGS'

// open tasks
export const SAVE_TASK_FILTER_OPTIONS = 'SAVE_TASK_FILTER_OPTIONS'
export const UPDATE_TASK_FILTERS = 'UPDATE_TASK_FILTERS'
export const UPDATE_TASK_PARAMS = 'UPDATE_TASK_PARAMS'
export const UPDATE_TASK_RESULTS = 'UPDATE_TASK_RESULTS'
export const UPDATE_TASK_FILTER_TAGS = 'UPDATE_TASK_FILTER_TAGS'

// url
export const SYNC_URL_SEARCH_PARAMS = 'SYNC_URL_SEARCH_PARAMS'
