/* eslint-disable linebreak-style */
module.exports = {
  list: [
    { id: 'accesskeys', weight: 0, group: 'a11y-navigation' },
    { id: 'aria-allowed-attr', weight: 3, group: 'a11y-aria' },
    { id: 'aria-required-attr', weight: 2, group: 'a11y-aria' },
    { id: 'aria-required-children', weight: 5, group: 'a11y-aria' },
    { id: 'aria-required-parent', weight: 2, group: 'a11y-aria' },
    { id: 'aria-roles', weight: 3, group: 'a11y-aria' },
    { id: 'aria-valid-attr-value', weight: 2, group: 'a11y-aria' },
    { id: 'aria-valid-attr', weight: 5, group: 'a11y-aria' },
    { id: 'audio-caption', weight: 0, group: 'a11y-audio-video' },
    { id: 'button-name', weight: 10, group: 'a11y-names-labels' },
    { id: 'bypass', weight: 10, group: 'a11y-navigation' },
    { id: 'color-contrast', weight: 6, group: 'a11y-color-contrast' },
    { id: 'definition-list', weight: 0, group: 'a11y-tables-lists' },
    { id: 'dlitem', weight: 0, group: 'a11y-tables-lists' },
    { id: 'document-title', weight: 2, group: 'a11y-names-labels' },
    { id: 'duplicate-id', weight: 5, group: 'a11y-best-practices' },
    { id: 'frame-title', weight: 5, group: 'a11y-names-labels' },
    { id: 'html-has-lang', weight: 4, group: 'a11y-language' },
    { id: 'html-lang-valid', weight: 0, group: 'a11y-language' },
    { id: 'image-alt', weight: 8, group: 'a11y-names-labels' },
    { id: 'input-image-alt', weight: 0, group: 'a11y-names-labels' },
    { id: 'label', weight: 0, group: 'a11y-names-labels' },
    { id: 'layout-table', weight: 0, group: 'a11y-tables-lists' },
    { id: 'link-name', weight: 9, group: 'a11y-names-labels' },
    { id: 'list', weight: 5, group: 'a11y-tables-lists' },
    { id: 'listitem', weight: 4, group: 'a11y-tables-lists' },
    { id: 'meta-refresh', weight: 0, group: 'a11y-best-practices' },
    { id: 'meta-viewport', weight: 3, group: 'a11y-best-practices' },
    { id: 'object-alt', weight: 0, group: 'a11y-names-labels' },
    { id: 'tabindex', weight: 4, group: 'a11y-navigation' },
    { id: 'td-headers-attr', weight: 0, group: 'a11y-tables-lists' },
    { id: 'th-has-data-cells', weight: 0, group: 'a11y-tables-lists' },
    { id: 'valid-lang', weight: 0, group: 'a11y-language' },
    { id: 'video-caption', weight: 0, group: 'a11y-audio-video' },
    { id: 'video-description', weight: 0, group: 'a11y-audio-video' },
    { id: 'logical-tab-order', weight: 0, group: 'miscellaneous' },
    { id: 'focusable-controls', weight: 0, group: 'miscellaneous' },
    { id: 'interactive-element-affordance', weight: 0, group: 'miscellaneous' },
    { id: 'managed-focus', weight: 0, group: 'miscellaneous' },
    { id: 'focus-traps', weight: 0, group: 'miscellaneous' },
    { id: 'custom-controls-labels', weight: 0, group: 'miscellaneous' },
    { id: 'custom-controls-roles', weight: 0, group: 'miscellaneous' },
    { id: 'visual-order-follows-dom', weight: 0, group: 'miscellaneous' },
    { id: 'offscreen-content-hidden', weight: 0, group: 'miscellaneous' },
    { id: 'heading-levels', weight: 0, group: 'miscellaneous' },
    { id: 'use-landmarks', weight: 0, group: 'miscellaneous' }
  ]
}
